### PR TITLE
update_all_projects: re-install python projects

### PR DESCRIPTION
**Pull request by jonasdn**

### CODE REVIEW

**Comment by jonasdn** [comment]
With this I get an error though:

One when running `pip3 install`:
error1

And one when starting the `cfclient`:
error2

Any ideas?

**Comment by jonasdn** [comment]
When force-installing the lib _after_ the client it downloads and installs a version of numpy > 19 and the client croaks. Seems like numpy 1.20 was recently (2021.1) released. Should the client bumpt it's requirement to >= 1.19.2 instead of ~=1.19.2?

**Comment by jonasdn** [comment]
Or we do it like in the commit added, explicitly install the lib before the client. That works for me and I can connect to a crazyflie with the client after running the `update_all_projects.sh` script.

**Comment by ataffanel** [comment]
> When force-installing the lib after the client it downloads and installs a version of numpy > 19 and the client croaks. Seems like numpy 1.20 was recently (2021.1) released. Should the client bump its requirement to >= 1.19.2 instead of ~=1.19.2?

Or ~=1.20? >= can be a bit dangerous since it will allow incompatible versions.

> Or we do it like in the commit added, explicitly install the lib before the client. That works for me and I can connect to a crazyflie with the client after running the `update_all_projects.sh` script.

Explicit works for me. As it is right now we will have to re-build a VM if we add a new python project anyway so we do not have to update in a loop.

**Pull request merged**
