### PR TITLE
Eclipse - Fix openocd debug path

### PR DESCRIPTION
**Pull request by NicksonYap**
Fixes https://github.com/bitcraze/bitcraze-vm/issues/39

### CODE REVIEW

**Comment by knmcguire** [comment]
Hi Nickson, thanks for looking into this. I will try to confirm this fix on my computer today or tomorrow.

**Comment by knmcguire** [comment]
I build the VM and checked it out, but It seems like all of the predefined configurations for debugging has disappearance from eclipse. Have you tried to build the VM and tried it out for yourself?

**Comment by NicksonYap** [comment]
I appologize, I wasn't able to get the build running so I just searched for all possible places where the config could be defined and replace with the correct one

Building issue: https://github.com/bitcraze/bitcraze-vm/issues/43

**Comment by NicksonYap** [comment]
#43 is not allowing me to build, so i can't actually test if the fix is working
@knmcguire tested that it's not working so PR needs to be cancelled or on hold until i can build, make corrections and test

**Comment by krichardsson** [comment]
OK, thanks for the update.

**Comment by knmcguire** [comment]
Any update on this? Do you need more time or maybe it's better to start a new pull request on this?

**Comment by NicksonYap** [comment]
@knmcguire yeah, i didn't have time to fix this, I'll create new PR when it's actually fixed.

**Pull request closed without merging**
